FROM debian:bookworm-slim
LABEL org.opencontainers.image.source=https://github.com/mikemoraned/bobby
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
