ARG BOBBY_CHEF=ghcr.io/mikemoraned/bobby/bobby-chef:latest
ARG BOBBY_RUNNER=ghcr.io/mikemoraned/bobby/bobby-runner:latest

FROM ${BOBBY_CHEF} AS builder
COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,target=/usr/local/cargo/git,sharing=locked \
    cargo build --release --bin skeet-feed

FROM ${BOBBY_RUNNER} AS runner

COPY --from=builder /build/target/release/skeet-feed /usr/local/bin/skeet-feed

CMD ["skeet-feed"]
