FROM rust:1.94-bookworm AS builder

WORKDIR /build

COPY . .
RUN cargo build --release --bin skeet-feed

FROM debian:bookworm-slim AS runner

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /build/target/release/skeet-feed /usr/local/bin/skeet-feed

CMD ["skeet-feed"]
