cluster_name: bobby
kubeconfig_path: "./infra/kubeconfig"
k3s_version: v1.32.0+k3s1

networking:
  ssh:
    port: 22
    use_agent: false
    public_key_path: "./infra/ssh/id_ed25519.pub"
    private_key_path: "./infra/ssh/id_ed25519"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api:
      - 0.0.0.0/0

schedule_workloads_on_masters: true
protect_against_deletion: false

masters_pool:
  instance_type: cax21
  instance_count: 1
  location: fsn1

worker_node_pools: []
