[package]
name = "observability"
version.workspace = true
edition.workspace = true

[dependencies]
chrono = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
shared = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[build-dependencies]
build-support = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
