apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-exporter
  labels:
    app: cloudflare-exporter
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: cloudflare-exporter
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: ghcr-pull-secret
          containers:
            - name: cloudflare-exporter
              image: ghcr.io/mikemoraned/bobby/cloudflare-exporter:${IMAGE_TAG}
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh", "-c"]
              args:
                - sync
                    --from $(date -u -d '11 minutes ago' '+%Y-%m-%dT%H:%M:%SZ')
                    --to   $(date -u -d '1 minute ago'  '+%Y-%m-%dT%H:%M:%SZ')
              resources:
                requests:
                  memory: "64Mi"
                limits:
                  memory: "128Mi"
              env:
                - name: BOBBY_CLOUDFLARE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: bobby-cloudflare-analytics-token
                      key: password
                - name: BOBBY_CLOUDFLARE_ACCOUNT_TAG
                  valueFrom:
                    secretKeyRef:
                      name: bobby-cloudflare-account-tag
                      key: password
                - name: BOBBY_PROM_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: bobby-grafanacloud-prom-endpoint
                      key: password
                - name: BOBBY_PROM_AUTH
                  valueFrom:
                    secretKeyRef:
                      name: bobby-grafanacloud-prom-auth
                      key: password
                - name: RUST_LOG
                  value: "info"
