apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-r2-endpoint
spec:
  itemPath: "vaults/Dev/items/hom-bobby-r2-local-rw-endpoint"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-r2-access-key-id
spec:
  itemPath: "vaults/Dev/items/hom-bobby-r2-local-rw-id"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-r2-secret-access-key
spec:
  itemPath: "vaults/Dev/items/hom-bobby-r2-local-rw-key"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-sse-c-key
spec:
  itemPath: "vaults/Dev/items/n2dy5qktxi7k3ukqinoym4l6nq"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-openai-api-key
spec:
  itemPath: "vaults/Dev/items/hom-bobby-openai-key"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-otel-headers
spec:
  itemPath: "vaults/Dev/items/hom-bobby-hcoltp-local-ingest"
