apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-r2-endpoint
  namespace: production
spec:
  itemPath: "vaults/Dev/items/hom-bobby-r2-local-rw-endpoint"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-r2-access-key-id
  namespace: production
spec:
  itemPath: "vaults/Dev/items/hom-bobby-r2-local-rw-id"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-r2-secret-access-key
  namespace: production
spec:
  itemPath: "vaults/Dev/items/hom-bobby-r2-local-rw-key"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-sse-c-key
  namespace: production
spec:
  itemPath: "vaults/Dev/items/n2dy5qktxi7k3ukqinoym4l6nq"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-redis-publish-url
  namespace: production
spec:
  itemPath: "vaults/Dev/items/bobby-upstash-redis-publish-tcp-url"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-openai-api-key
  namespace: production
spec:
  itemPath: "vaults/Dev/items/hom-bobby-openai-key"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-grafana-oltp-endpoint
  namespace: production
spec:
  itemPath: "vaults/Dev/items/bobby-grafanacloud-oltp-endpoint"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-grafana-oltp-headers
  namespace: production
spec:
  itemPath: "vaults/Dev/items/bobby-grafanacloud-oltp-headers"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-cloudflare-analytics-token
  namespace: production
spec:
  itemPath: "vaults/Dev/items/bobby-cloudflare-analytics-token"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-cloudflare-account-tag
  namespace: production
spec:
  itemPath: "vaults/Dev/items/bobby-cloudflare-account-tag"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-grafanacloud-prom-endpoint
  namespace: production
spec:
  itemPath: "vaults/Dev/items/bobby-grafanacloud-prom-endpoint"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-grafanacloud-prom-auth
  namespace: production
spec:
  itemPath: "vaults/Dev/items/bobby-grafanacloud-prom-auth"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bobby-openai-admin-usage-key
  namespace: production
spec:
  itemPath: "vaults/Dev/items/bobby-openai-admin-usage-key"
